name: HunterVsHunted
version: 1.0
description: Hunter vs Hunted
author: Leee Leee
website: denmc.online

main: hvh.org.Main

commands:
    hvh:
        description: Hunter vs Hunted
        permission: spigotplugin.hvh
        usage: /<command>

permissions: {}
